dist: bionic
language: python
python:
  - 3.6
cache: pip
addons:
  postgresql: 9.5
  apt:
    packages:
      - bc
      - chromium-browser
      - snakefood
      - software-properties-common
services:
  - docker
env:
  - SCRIPT=./scripts/travis TESTENV=travis-postgresql DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=postgres:PASSWORD=squad:HOST=127.0.0.1:PORT=5432 INSTALLPIP=yes START_LAVA=yes
  - SCRIPT=./scripts/travis TESTENV=travis-sqlite3 DATABASE= SQUAD_EXCLUDE_TEST_TAGS=skip_sqlite INSTALLPIP=yes START_LAVA=yes
  - SCRIPT="./scripts/check-ignore"
  - SCRIPT="./dev-docker ./manage.py test -v 3"
  - SCRIPT="./scripts/test-docker"
  - SCRIPT="./manage.py compilemessages" INSTALLPIP=yes
  - SCRIPT="docker run -v $(pwd):/squad --workdir /squad fsfe/reuse lint"
  - SCRIPT="./scripts/pytest" DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=postgres:PASSWORD=squad:HOST=127.0.0.1:PORT=5432 INSTALLPIP=yes

before_install:
  - if test -n "$DATABASE"; then ./scripts/travis-postgresql; fi

before_script:
  - if test -n "$START_LAVA"; then ./scripts/travis-lava; fi

after_script:
  - if test -n "$START_LAVA"; then ./scripts/travis-lava -s; fi

install:
  - |
    if test "$INSTALLPIP" = "yes"; then
      pip install --upgrade setuptools
      pip install -r requirements-dev.txt
      pip freeze
      sudo apt-get install nodejs npm
      npm install
    fi

script:
  - $SCRIPT

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#linaro-qa"
