dist: trusty
language: python
python:
  - 3.5
cache: pip
addons:
  postgresql: 9.5
  apt:
    packages:
      - bc
      - chromium-browser
      - snakefood
      - software-properties-common
env:
  - DJANGO=1.11 TESTENV=travis-postgresql DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=postgres:PASSWORD=squad:HOST=127.0.0.1:PORT=5432
  - DJANGO=1.11 TESTENV=travis-sqlite3 DATABASE=

before_install:
  - if test -n "$DATABASE"; then ./scripts/travis-postgresql; fi

install:
  - pip install --upgrade setuptools
  - ./scripts/travis-django
  - pip install -r requirements-dev.txt
  - pip freeze
  - sudo apt-get install nodejs npm
  - npm install
  - npm set ca null
  - sudo npm install -g karma-cli

script:
  - ./scripts/travis

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#linaro-qa"
