#!/bin/sh

set -eu


basedir="$(readlink -f "$(dirname $0)")"
tmpdir="$basedir"/tmp
datadir="$tmpdir"/data
mkdir -p "$datadir"

dockerfile="$datadir"/../Dockerfile.dev
(
  sed -e '1,/WORKDIR/!d' "$basedir"/Dockerfile
  echo 'RUN apt-get install -qy python3-ipython python3-pickleshare python3-django-extensions python3-werkzeug flake8 python3-mock snakefood'
  echo "RUN groupadd -g $(id -g) $(id -gn)"
  echo "RUN useradd -m -u $(id -u) -g $(id -g) -s /bin/bash ${USER}"
  echo "USER ${USER}"
  echo 'CMD sh -c "./manage.py test && ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"'
) > "$dockerfile"

docker build -t squad/dev -f "$dockerfile" .

exec docker run \
  --env=XDG_DATA_HOME=/app/tmp/data \
  --publish=8000:8000 \
  --volume="$basedir":/app \
  --rm \
  -it squad/dev "$@"
