# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='metrics_file',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='tests_file',
            field=models.TextField(null=True),
        ),
    ]
