# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160525_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='log_file',
            field=models.TextField(null=True),
        ),
    ]
