# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0003_testrun_log_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
