# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testrun_data_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_pass', models.IntegerField(default=0)),
                ('tests_fail', models.IntegerField(default=0)),
                ('metrics_summary', models.FloatField(default=0.0)),
                ('suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Suite')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.TestRun')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set([('test_run', 'suite')]),
        ),
    ]
