# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='status_recorded',
            field=models.BooleanField(default=False),
        ),
    ]
