# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_testrun_status_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL(
            "UPDATE core_testrun SET datetime = created_at",
            reverse_sql="SELECT 1",
        ),
        migrations.AlterField(
            model_name='testrun',
            name='datetime',
            field=models.DateTimeField(null=False),
        )
    ]
