# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testrun_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='build_url',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='job_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='job_status',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='job_url',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
