# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_testrun_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL(
            "UPDATE core_build SET datetime = created_at",
            reverse_sql="SELECT 1",
        ),
        migrations.AlterField(
            model_name='build',
            name='datetime',
            field=models.DateTimeField(null=False),
        ),
    ]
