# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_testrun_resubmit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='metadata_file',
            field=models.TextField(null=True),
        ),
    ]
