# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_testrun_metadata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('data', models.BinaryField(default=None)),
                ('length', models.IntegerField(default=None)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.TestRun')),
            ],
        ),
    ]
