# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_build_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['version']},
        ),
    ]
