# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_build_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.Project'),
        ),
    ]
