# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_global_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Build')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='core.ProjectStatus')),
            ],
        ),
    ]
