# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='build_completion_threshold',
            field=models.IntegerField(default=120),
        ),
    ]
