# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_testrun_result_accept_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notification_strategy',
            field=models.CharField(choices=[('all', 'All builds'), ('change', 'Only on change')], default='all', max_length=32),
        ),
    ]
