# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 15:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_project_notification_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='slug',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*')]),
        ),
        migrations.AlterField(
            model_name='suite',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='suite',
            name='slug',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*')]),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
