# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_subscription_email_formats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='build_completion_threshold',
        ),
    ]
