# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_project_build_completion_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='expected_test_runs',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
