# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_environment_expected_test_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
