# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_drop_debversion'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE core_build SET version = name WHERE name != ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
