# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_build_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='tests_skip',
            field=models.IntegerField(default=0),
        ),
    ]
