# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_populate_project_status_cache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['group', 'slug']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['name']},
        ),
    ]
