# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_orderings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='html',
        ),
    ]
