# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_subscription_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
