# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_projectstatus_notified'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE core_projectstatus SET notified = (2>1);",
            reverse_sql="SELECT 1",
        ),
    ]
