# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_set_projectstatus_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='build',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Build'),
        ),
    ]
