# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 13:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_project_html_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1024, validators=[django.core.validators.EmailValidator()])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_subscriptions', to='core.Project')),
            ],
        ),
    ]
