# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_adminsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
