# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_projectstatus_last_updated'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE core_projectstatus SET last_updated = created_at",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
