# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_moderate_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name_plural': 'Project statuses'},
        ),
    ]
