# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_projectstatus_previous'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('plain_text', models.TextField(help_text='Jinja2 template for text/plain content')),
                ('html', models.TextField(blank=True, help_text='Jinja2 template for text/html content', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='custom_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EmailTemplate'),
        ),
    ]
