# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20170831_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='suiteversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SuiteVersion'),
        ),
    ]
