# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_custom_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, help_text='Jinja2 template for subject (single line)', max_length=1024, null=True),
        ),
    ]
