# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='has_metrics',
            field=models.BooleanField(default=False),
        ),
    ]
