# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_populate_projectstatus_has_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='important_metadata_keys',
            field=models.TextField(blank=True, null=True),
        ),
    ]
