# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_project_important_metadata_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
