# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_project_wait_before_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notification_timeout',
            field=models.IntegerField(help_text='Force sending build notifications after this many seconds', null=True),
        ),
    ]
