# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_project_notification_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='notified_on_timeout',
            field=models.BooleanField(default=False),
        ),
    ]
