# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_projectstatus_notified_on_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
