# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_environment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
