# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_accept_blank_suite_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.Suite')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='suiteversion',
            unique_together=set([('suite', 'version')]),
        ),
        migrations.AddField(
            model_name='status',
            name='suite_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SuiteVersion'),
        ),
    ]
