# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_migrate_old_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
