# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 15:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20180420_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*')]),
        ),
        migrations.AlterField(
            model_name='suite',
            name='slug',
            field=models.CharField(db_index=True, max_length=256, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*')]),
        ),
        migrations.AlterField(
            model_name='suitemetadata',
            name='kind',
            field=models.CharField(choices=[('suite', 'Suite'), ('test', 'Test'), ('metric', 'Metric')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='suitemetadata',
            name='name',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='suitemetadata',
            name='suite',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
