# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 02:34
from __future__ import unicode_literals

from django.db import migrations
import squad.core.plugins


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enabled_plugins_list',
            field=squad.core.plugins.PluginListField(null=True),
        ),
    ]
