# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import squad.core.plugins


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_update_project_enabled_plugin_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('username', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('token', models.CharField(max_length=1024)),
                ('implementation', squad.core.plugins.PluginField(default='null')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='patch_baseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Build'),
        ),
        migrations.AddField(
            model_name='build',
            name='patch_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='patch_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PatchSource'),
        ),
    ]
