# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_knownissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='test_runs_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='test_runs_incomplete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='test_runs_total',
            field=models.IntegerField(default=0),
        ),
    ]
