# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 10:37
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0079_init_cache_test_run_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('project', 'user')]),
        ),
    ]
