# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_init_cache_test_run_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=40, null=True)),
                ('txt', models.CharField(blank=True, max_length=40, null=True)),
                ('html', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='core.ProjectStatus')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notificationdelivery',
            unique_together=set([('status', 'subject', 'txt', 'html')]),
        ),
    ]
