# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import squad.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_rename_knownissue_environments'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='fixes',
            field=models.TextField(blank=True, null=True, validators=[squad.core.utils.yaml_validator]),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='regressions',
            field=models.TextField(blank=True, null=True, validators=[squad.core.utils.yaml_validator]),
        ),
    ]
