# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_projectstatus_regressions_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='tests_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='tests_pass',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='tests_skip',
            field=models.IntegerField(default=0),
        ),
    ]
