# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_user_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='has_known_issues',
            field=models.NullBooleanField(),
        ),
    ]
