# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 22:47
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


SQL = """
UPDATE core_test
SET has_known_issues = (2>1)
FROM core_test_known_issues
WHERE core_test_known_issues.test_id = core_test.id
"""


SQLITE = 'sqlite3' in settings.DATABASES['default']['ENGINE']


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_test_has_known_issues'),
    ]

    if SQLITE:
        operations = []
    else:
        operations = [
            migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop),
        ]
