# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_populate_test_has_known_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.ProjectStatus'),
        ),
    ]
