# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_notification_delivery_remove_unique_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('build', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Build')),
            ],
        ),
    ]
