# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_populatehistoricalemailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_retention_days',
            field=models.IntegerField(default=0, help_text='Delete builds older than this number of days. Set to 0 or any negative number to disable.'),
        ),
    ]
