# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_project_data_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='keep_data',
            field=models.BooleanField(
                default=False,
                help_text='Keep this build data even after the project data retention period has passed',
            ),
        ),
    ]
