# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-16 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_build_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
