# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_blank_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('value', models.FloatField()),
                ('is_higher_better', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='metricthreshold',
            unique_together=set([('project', 'name')]),
        ),
    ]
