# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import squad.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_metric_is_outlier'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_settings',
            field=models.TextField(blank=True, null=True, validators=[squad.core.utils.yaml_validator]),
        ),
    ]
