# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_project_project_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='metrics_summary',
            field=models.FloatField(null=True),
        ),
    ]
