# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-13 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import squad.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_delayedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delayedreport',
            name='error_message',
            field=models.TextField(blank=True, null=True, validators=[squad.core.utils.yaml_validator]),
        ),
    ]
