# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-20 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_delayed_report_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedreport',
            name='output_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
