# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import squad.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_move_notification_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html',
            field=models.TextField(blank=True, help_text='Jinja2 template for text/html content', null=True, validators=[squad.core.utils.jinja2_validator]),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='plain_text',
            field=models.TextField(help_text='Jinja2 template for text/plain content', validators=[squad.core.utils.jinja2_validator]),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, help_text='Jinja2 template for subject (single line)', max_length=1024, null=True, validators=[squad.core.utils.jinja2_validator]),
        ),
        migrations.AlterField(
            model_name='historicalemailtemplate',
            name='html',
            field=models.TextField(blank=True, help_text='Jinja2 template for text/html content', null=True, validators=[squad.core.utils.jinja2_validator]),
        ),
        migrations.AlterField(
            model_name='historicalemailtemplate',
            name='plain_text',
            field=models.TextField(help_text='Jinja2 template for text/plain content', validators=[squad.core.utils.jinja2_validator]),
        ),
        migrations.AlterField(
            model_name='historicalemailtemplate',
            name='subject',
            field=models.CharField(blank=True, help_text='Jinja2 template for subject (single line)', max_length=1024, null=True, validators=[squad.core.utils.jinja2_validator]),
        ),
    ]
