# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_move_users_from_django_groups_to_squad_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user_groups',
        ),
    ]
