# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 14:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_remove_group_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNamespace',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.group',),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^~?[a-zA-Z0-9][a-zA-Z0-9_.-]*')]),
        ),
    ]
