# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 15:19
from __future__ import unicode_literals

from django.db import migrations
import squad.core.plugins


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_group_project_blank_name_and_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enabled_plugins_list',
            field=squad.core.plugins.PluginListField(blank=True, null=True),
        ),
    ]
