# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 15:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_project_enabled_plugin_list_can_be_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*$')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^~?[a-zA-Z0-9][a-zA-Z0-9_.-]*$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*$')]),
        ),
        migrations.AlterField(
            model_name='suite',
            name='slug',
            field=models.CharField(db_index=True, max_length=256, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9_.-]*$')]),
        ),
    ]
