# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_drop_obsolete_token_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Makes the project hidden from the group page by default'),
        ),
    ]
