# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import squad.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_summary', models.FloatField(null=True)),
                ('has_metrics', models.BooleanField(default=False)),
                ('tests_pass', models.IntegerField(default=0)),
                ('tests_fail', models.IntegerField(default=0)),
                ('tests_xfail', models.IntegerField(default=0)),
                ('tests_skip', models.IntegerField(default=0)),
                ('test_runs_total', models.IntegerField(default=0)),
                ('test_runs_completed', models.IntegerField(default=0)),
                ('test_runs_incomplete', models.IntegerField(default=0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_summary', to='core.Build')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Environment')),
            ],
            bases=(models.Model, squad.core.models.TestSummaryBase),
        ),
    ]
