# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-25 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_buildsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchsource',
            name='_password',
            field=models.CharField(blank=True, db_column='password', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patchsource',
            name='url',
            field=models.URLField(help_text="scheme://host, ex: 'http://github.com', 'ssh://gerrit.host, etc'"),
        ),
    ]
