# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-02 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import squad.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_add_password_patchsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchsource',
            name='token',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='patchsource',
            name='url',
            field=squad.core.models.CustomURLField(help_text="scheme://host, ex: 'http://github.com', 'ssh://gerrit.host, etc'"),
        ),
    ]
