# Generated by Django 2.2.5 on 2019-10-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_fix_patchsource_url_and_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='metadata',
            field=models.ForeignKey(limit_choices_to={'kind': 'metric'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.SuiteMetadata'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='metadata',
            field=models.ForeignKey(limit_choices_to={'kind': 'suite'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.SuiteMetadata'),
        ),
        migrations.AlterField(
            model_name='test',
            name='metadata',
            field=models.ForeignKey(limit_choices_to={'kind': 'test'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.SuiteMetadata'),
        ),
    ]
