# Generated by Django 2.2.5 on 2019-10-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_django_upgrade_missing_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='expected_test_runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
