# Generated by Django 2.2.6 on 2020-03-23 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_fix_missing_status_has_metrics_for_testruns'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricthreshold',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Environment'),
        ),
        migrations.AlterUniqueTogether(
            name='metricthreshold',
            unique_together=set(),
        ),
    ]
