# Generated by Django 2.2.6 on 2020-02-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_metric_thresholds_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricthreshold',
            name='project',
        ),
        migrations.AlterField(
            model_name='metricthreshold',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Environment'),
        ),
    ]
