# Generated by Django 2.2.11 on 2020-04-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_metric_thresholds_remove_proj_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='notified_on_timeout',
            field=models.NullBooleanField(default=None),
        ),
    ]
