# Generated by Django 2.2.12 on 2020-07-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_create_squad_auth_group_and_add_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='mimetype',
            field=models.CharField(default='application/octet-stream', max_length=128),
        ),
    ]
