# Generated by Django 2.2.15 on 2020-09-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_remove_test_name_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='metrics_file',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='tests_file',
        ),
    ]
