# Generated by Django 2.2.15 on 2020-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_append_project_permissions_to_squad_auth_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
