# Generated by Django 2.2.16 on 2020-09-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_remove_test_name_column'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='testrun',
            index_together={('id', 'environment')},
        ),
    ]
