# Generated by Django 2.2.13 on 2020-09-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_longer_metric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='access',
            field=models.CharField(choices=[('member', 'Member'), ('submitter', 'Result submitter'), ('privileged', 'Privileged'), ('admin', 'Administrator')], default='member', max_length=10),
        ),
    ]
