# Generated by Django 2.2.12 on 2020-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_migrate_submitters_to_privileged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchsource',
            name='token',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
