# Generated by Django 2.2.13 on 2020-10-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_patchsource_token_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='unit',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
