# Generated by Django 2.2.16 on 2020-10-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_metric_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['metadata__name']},
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=256, db_index=True, null=True, default=None, blank=True),
        ),
    ]
