# Generated by Django 2.2.16 on 2020-10-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_nullable_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchsource',
            name='_password',
            field=models.CharField(blank=True, db_column='password', max_length=256, null=True),
        ),
    ]
