# Generated by Django 2.2.12 on 2020-09-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_remove_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='log_file_storage',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='testrun',
            name='metrics_file_storage',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='testrun',
            name='tests_file_storage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
