# Generated by Django 2.2.16 on 2020-11-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_attachment_data_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginScratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.TextField(blank=True, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Build')),
            ],
        ),
    ]
