# Generated by Django 2.2.16 on 2020-11-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_pluginscratch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrun',
            old_name='log_file',
            new_name='old_log_file',
        ),
        migrations.RenameField(
            model_name='testrun',
            old_name='metrics_file',
            new_name='old_metrics_file',
        ),
        migrations.RenameField(
            model_name='testrun',
            old_name='tests_file',
            new_name='old_tests_file',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='data',
            new_name='old_data',
        ),
    ]
