# Generated by Django 2.2.17 on 2020-12-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0146_deprecate_testrun_and_attachment_data_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.Build'),
        ),
        migrations.AddField(
            model_name='test',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.Environment'),
        ),
    ]
