# Generated by Django 2.2.17 on 2021-01-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_build_patch_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='notification_strategy',
            field=models.CharField(choices=[('all', 'All builds'), ('change', 'Only on change'), ('regression', 'Only on regression'), ('error', 'Only on infrastructure error')], default='all', max_length=32),
        ),
    ]
