# Generated by Django 2.2.17 on 2021-01-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='patch_notified',
            field=models.BooleanField(default=False),
        ),
    ]
