# Generated by Django 2.2.17 on 2021-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_callback_make_response_content_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='force_finishing_builds_on_timeout',
            field=models.BooleanField(default=False, help_text='Forces builds to finish when "Notification timeout" is reached'),
        ),
    ]
