# Generated by Django 2.2.28 on 2022-05-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_project_add_build_confidence_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalemailtemplate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical email template', 'verbose_name_plural': 'historical email templates'},
        ),
        migrations.AlterField(
            model_name='historicalemailtemplate',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
