# Generated by Django 2.2.16 on 2022-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_buildsummary_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='is_release',
            field=models.BooleanField(default=False, help_text='Indication whether the build is considered a release'),
        ),
        migrations.AddField(
            model_name='build',
            name='release_label',
            field=models.CharField(blank=True, help_text='Name or label applied to the release build', max_length=64, null=True),
        ),
    ]
