# Generated by Django 4.0.4 on 2022-11-22 13:23

from django.db import migrations, models
import squad.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_add_project_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='settings',
            field=models.TextField(blank=True, null=True, validators=[squad.core.utils.yaml_validator]),
        ),
    ]
