#!/bin/sh

set -exu

./manage.py migrate
./manage.py shell --no-color --plain  -c "exec(open('$(dirname $0)/setup.py').read())"

./manage.py runserver &
trap 'pkill -f runserver' INT TERM EXIT

sleep 3
AUTH_TOKEN=key1 ./scripts/testdata/gen-test-data team1 project1
AUTH_TOKEN=key2 ./scripts/testdata/gen-test-data team2 project2
