#!/bin/sh

set -exu

./manage.py migrate

./manage.py runserver &
trap 'pkill -f runserver' INT TERM EXIT

sleep 3

./scripts/testdata/gen-test-data team1 project1 board1
./scripts/testdata/gen-test-data team1 project1 board2
./scripts/testdata/gen-test-data team2 project2 board1
./scripts/testdata/gen-test-data team2 project2 board2
./scripts/testdata/gen-test-data team3 project3 board1
./scripts/testdata/gen-test-data team3 project3 board2
