# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='listener_filter',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='backend',
            name='listener_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
