# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0002_auto_20170406_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='name',
            field=models.CharField(default='unnamed', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
