# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0003_backend_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='failure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
