# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0004_testjob_failure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjob',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
