# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0004_testjob_failure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backend',
            name='listener_filter',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='listener_url',
        ),
    ]
