# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0005_remove_listener_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='implementation_type',
            field=models.CharField(choices=[('lava', 'lava'), ('null', 'null')], default='null', max_length=64),
        ),
    ]
