# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0006_simplify_backend_loading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjob',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
