# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_unique_testrun_job_id'),
        ('ci', '0007_auto_20170517_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='testrun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_jobs', to='core.TestRun'),
        ),
    ]
