# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0009_slug_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='can_resubmit',
            field=models.BooleanField(default=False),
        ),
    ]
