# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0010_testjob_can_resubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='resubmitted_count',
            field=models.IntegerField(default=0),
        ),
    ]
