# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0011_testjob_resubmitted_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjob',
            name='build',
            field=models.CharField(max_length=100),
        ),
    ]
