# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0012_testjob_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
