# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0015_testjob_populate_target_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='max_fetch_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
