# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0016_backend_max_fetch_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='fetch_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
