# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import squad.ci.models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0019_add_fake_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='backend_settings',
            field=models.TextField(blank=True, null=True, validators=[squad.ci.models.yaml_validator]),
        ),
    ]
