# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0020_backend_settings_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='parent_job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resubmitted_jobs', to='ci.TestJob'),
        ),
    ]
