# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0021_testjob_parent_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='poll_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
