# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0022_backend_poll_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testjob',
            name='build',
        ),
    ]
