# Generated by Django 2.2.6 on 2019-10-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0024_fix_testjob_environment_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='listen_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
