# Generated by Django 4.0.4 on 2022-11-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0027_add_tuxsuite_implementation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjob',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='testjob',
            index=models.Index(fields=['submitted', 'fetched'], name='ci_testjob_submitt_e51225_idx'),
        ),
    ]
