# Generated by Django 4.2 on 2023-12-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ci", "0029_create_testjob_results_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="testjob",
            name="subtasks_count",
            field=models.IntegerField(default=0),
        ),
    ]
