#!/bin/sh

set -eu

tests_file=${1:-.tests}
if [ ! -f "$tests_file" ]; then
  (./manage.py test --noinput -v 2 2>&1 || true) > .tests
fi

(
  echo "{"
  awk 'BEGIN { s = "" }/^test_/ { gsub("[()]", "", $2); r = "pass"; if ($4 != "ok") { r = "fail" }; print(s "\"" $2 "." $1 "\"" ": \"" r "\"" ); s = ","  }' "$tests_file"
  echo "}"
) | jq ''
