#!/bin/bash

set -eu
set -o pipefail

git fetch origin cache/static
git archive FETCH_HEAD | tar xaf -

./manage.py test --noinput -v 2 2>&1 | tee .tests

echo "{
  \"job_id\": \"$TRAVIS_JOB_NUMBER\",
  \"job_url\": \"https://travis-ci.org/Linaro/squad/jobs/$TRAVIS_JOB_ID\",
  \"build_url\": \"https://travis-ci.org/Linaro/squad/builds/$TRAVIS_BUILD_ID\"
}" | jq '' > .metadata.json

SUBMIT_TO=${SUBMIT_TO:-https://squad.puzzle.analizo.org/api}

if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  ./scripts/dogfood "${SUBMIT_TO}" linaro-qa/squad "$TESTENV" "$TRAVIS_BUILD_NUMBER"
fi

! grep '^test_.*\\(ERROR\\|FAIL\\)' .tests
