#!/bin/sh

set -eu

echo "{
  \"job_id\": \"$TRAVIS_JOB_NUMBER\",
  \"job_url\": \"https://travis-ci.org/Linaro/squad/jobs/$TRAVIS_JOB_ID\",
  \"build_url\": \"https://travis-ci.org/Linaro/squad/builds/$TRAVIS_BUILD_ID\"
}" | jq ''
