#!/bin/bash

tag="$1"
v="${tag:1}"

# Push to PyPi
twine upload dist/*

# Push to dockerhub
echo 'Login to hub.docker.com:'
docker login
docker tag squadproject/squad:$v squadproject/squad:latest
docker push squadproject/squad:$v
docker push squadproject/squad:latest
